# Generated by Django 4.1.4 on 2022-12-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Traffic",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="main.user",
                    ),
                ),
                ("from_left", models.IntegerField(default=0)),
                ("from_right", models.IntegerField(default=0)),
                ("from_top", models.IntegerField(default=0)),
                ("from_bottom", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Traffic size",
                "verbose_name_plural": "Traffic sizes",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Site user", "verbose_name_plural": "Site users"},
        ),
        migrations.DeleteModel(
            name="Trafic",
        ),
    ]
