# Generated by Django 4.1.4 on 2022-12-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_traffic_alter_user_options_delete_trafic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traffic",
            name="from_bottom",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="from_left",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="from_right",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="from_top",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
