# Generated by Django 4.1.4 on 2023-01-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_results_user_results_traffic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speed", models.IntegerField()),
                (
                    "traffic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="main.traffic"
                    ),
                ),
            ],
        ),
    ]
