# Generated by Django 4.1.4 on 2022-12-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_traffic_from_bottom_alter_traffic_from_left_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
