# Generated by Django 4.1.4 on 2023-02-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_results_horizontal_collapse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speed", models.IntegerField()),
                ("iterations", models.IntegerField()),
                (
                    "traffic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="main.traffic"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Speed",
        ),
    ]
