# Generated by Django 4.1.4 on 2023-02-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_otherparam_delete_speed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otherparam",
            name="iterations",
            field=models.IntegerField(default=15),
        ),
    ]
