# Generated by Django 4.1.4 on 2023-03-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_otherparam_iterations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otherparam",
            name="speed",
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="from_bottom",
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="from_left",
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="from_right",
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="from_top",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
